### ISSUE TITLE
Add IRepos with CRUD methods for base enteties

### ISSUE THREAD

**Issue by MorphineForOdin** [MorphineForOdin/GoT2_LCG#10]

**Comment by iburkov** [comment]
User dapper  https://github.com/StackExchange/dapper-dot-net

**Comment by MorphineForOdin** [comment]
Review: https://github.com/MorphineForOdin/GoT2_LCG/commit/f2fd52d4ae0804e9e958c4852cded4473d307c93?diff=split

**Comment by MorphineForOdin** [comment]
Remove 'Base' sufix from Repo and Entity names
