### ISSUE TITLE
Populate SQL bootstrap scripts for ChallengeIcon and CardType

### ISSUE THREAD

**Issue by iburkov** [MorphineForOdin/GoT2_LCG#14]

**Comment by MorphineForOdin** [comment]
Review: https://github.com/MorphineForOdin/GoT2_LCG/commit/0810e0f6d4b0dcdace137d47c0d46191f828bb22?diff=split

**Comment by MorphineForOdin** [comment]
CR fixes: https://github.com/MorphineForOdin/GoT2_LCG/commit/25dcb15c0c4294e772003292df02010b7836a0d4?diff=split

**Comment by MorphineForOdin** [comment]
Code review passed
