### ISSUE TITLE
Implement Serilog logger

### ISSUE THREAD

**Issue by MorphineForOdin** [MorphineForOdin/GoT2_LCG#9]

**Comment by MorphineForOdin** [comment]
Info\debug\warn\error\critical

**Comment by MorphineForOdin** [comment]
Review: https://github.com/MorphineForOdin/GoT2_LCG/commit/ef2bf6335e8c14ec03ae7fce8d27b334f29f3f6f

**Comment by iburkov** [comment]
Added CR comments

**Comment by MorphineForOdin** [comment]
Updated review: https://github.com/MorphineForOdin/GoT2_LCG/commit/bbb90478dcdc02cd14db0c7e041e24175fb5a65a

**Comment by MorphineForOdin** [comment]
passed
